# Generated by Django 3.0.5 on 2020-08-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('agentId', models.IntegerField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=60)),
                ('website', models.EmailField(max_length=60)),
                ('facebook', models.EmailField(max_length=60)),
                ('twitter', models.EmailField(max_length=60)),
                ('instagram', models.EmailField(max_length=60)),
                ('photo', models.ImageField(blank=True, upload_to='blog_images')),
            ],
        ),
    ]
