# Generated by Django 3.0.5 on 2020-08-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agentId',
            field=models.CharField(max_length=150),
        ),
    ]
