# Generated by Django 3.0.5 on 2020-08-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200827_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='facebook',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='agent',
            name='instagram',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='agent',
            name='twitter',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='agent',
            name='website',
            field=models.CharField(max_length=60),
        ),
    ]
