# Generated by Django 3.0.5 on 2020-08-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200827_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('no_of_beds', models.IntegerField()),
                ('no_of_bathrooms', models.IntegerField()),
                ('parking_area', models.CharField(max_length=150)),
                ('lot_size', models.CharField(max_length=150)),
                ('property_id', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='property_images')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='app.Agent')),
            ],
        ),
    ]
