# Generated by Django 3.0.5 on 2020-09-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200831_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('months', models.IntegerField()),
                ('listing', models.IntegerField()),
                ('featured_listings', models.IntegerField()),
            ],
        ),
    ]
