# Generated by Django 3.0.5 on 2020-09-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='method',
            field=models.CharField(default='paypal', max_length=150),
            preserve_default=False,
        ),
    ]
